name: webview_auth_tizen
description: Social network authentication plugin using webview for Tizen.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.4
  webview_flutter_tizen: ^0.6.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: WebviewAuthTizenPlugin
        fileName: webview_auth_tizen_plugin.h
