name: desktop_webview_auth_tizen
description: A new Flutter plugin project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ewk_webview_flutter_tizen:
    path: /home/user/Tizen/projects/ewk_version/packages/ewk_webview_flutter
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  desktop_webview_auth: 0.0.9
flutter:

  plugin:
    platforms:
      tizen:
        pluginClass: DesktopWebviewAuthTizenPlugin
        fileName: desktop_webview_auth_tizen_plugin.h
